name: Run .bat file

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-bat:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run .bat file
        run: ./work.bat
